DATABASE_NAME = "somedbname"

DATABASE_PORT = 27017
DATABASE_HOST = "somedbhost"

AUTHENTICATE = False
DATABASE_USERNAME = ""
DATABASE_PASSWORD = ""



MIGRATE_TO_DATABASE_NAME = "somedbname"


MIGRATE_TO_DATABASE_PORT = 27017
MIGRATE_TO_DATABASE_HOST = "somedbhost"

MIGRATE_TO_AUTHENTICATE = True
MIGRATE_TO_DATABASE_USERNAME = "someusername"
MIGRATE_TO_DATABASE_PASSWORD = "someuserpassword"